export const MOVIE_FETCH_SUCCESS = "MOVIE_FETCH_SUCCESS";
export const MOVIE_FETCH_REQUEST = "MOVIE_FETCH_REQUEST";
export const MOVIE_FETCH_FAILED = "MOVIE_FETCH_FAILED";

export const TRAILER_FETCH_SUCCESS = "TRAILER_FETCH_SUCCESS";
export const TRAILER_FETCH_REQUEST = "TRAILER_FETCH_REQUEST";
export const TRAILER_FETCH_FAILED = "TRAILER_FETCH_FAILED";
export const TRAILER_FETCH_RESET = "TRAILER_FETCH_RESET";
