export const MOVIE_FETCH_SUCCESS = "MOVIE_FETCH_SUCCESS";
export const MOVIE_FETCH_REQUEST = "MOVIE_FETCH_REQUEST";
export const MOVIE_FETCH_FAILED = "MOVIE_FETCH_FAILED";

export const TRAILER_FETCH_SUCCESS = "TRAILER_FETCH_SUCCESS";
export const TRAILER_FETCH_REQUEST = "TRAILER_FETCH_REQUEST";
export const TRAILER_FETCH_FAILED = "TRAILER_FETCH_FAILED";
export const TRAILER_FETCH_RESET = "TRAILER_FETCH_RESET";

export const PLAY_FETCH_SUCCESS = "PLAY_FETCH_SUCCESS";
export const PLAY_FETCH_REQUEST = "PLAY_FETCH_REQUEST";
export const PLAY_FETCH_FAILED = "PLAY_FETCH_FAILED";
export const PLAY_FETCH_RESET = "PLAY_FETCH_RESET";

export const SERIES_FETCH_SUCCESS = "SERIES_FETCH_SUCCESS";
export const SERIES_FETCH_REQUEST = "SERIES_FETCH_REQUEST";
export const SERIES_FETCH_FAILED = "SERIES_FETCH_FAILED";

export const TV_TRAILER_FETCH_REQUEST = "TV_TRAILER_FETCH_REQUEST";
export const TV_TRAILER_FETCH_SUCCESS = "TV_TRAILER_FETCH_SUCCESS";
export const TV_TRAILER_FETCH_FAILED = "TV_TRAILER_FETCH_FAILED";
export const TV_TRAILER_FETCH_RESET = "TV_TRAILER_FETCH_RESET";

export const TV_PLAY_FETCH_SUCCESS = "TV_PLAY_FETCH_SUCCESS";
export const TV_PLAY_FETCH_REQUEST = "TV_PLAY_FETCH_REQUEST";
export const TV_PLAY_FETCH_FAILED = "TV_PLAY_FETCH_FAILED";
export const TV_PLAY_FETCH_RESET = "TV_PLAY_FETCH_RESET";

export const SERIES_DETAILS_FETCH_REQUEST = "SERIES_DETAILS_FETCH_REQUEST";
export const SERIES_DETAILS_FETCH_SUCCESS = "SERIES_DETAILS_FETCH_SUCCESS";
export const SERIES_DETAILS_FETCH_FAILED = "SERIES_DETAILS_FETCH_FAILED";

export const EPISODE_DETAILS_FETCH_REQUEST = "EPISODE_DETAILS_FETCH_REQUEST";
export const EPISODE_DETAILS_FETCH_SUCCESS = "EPISODE_DETAILS_FETCH_SUCCESS";
export const EPISODE_DETAILS_FETCH_FAILED = "EPISODE_DETAILS_FETCH_FAILED";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const GET_SEARCH_INPUT = "GET_SEARCH_INPUT";

export const SEARCH_QUERY_FETCH_REQUEST = "SEARCH_QUERY_FETCH_REQUEST";
export const SEARCH_QUERY_FETCH_SUCCESS = "SEARCH_QUERY_FETCH_SUCCESS";
export const SEARCH_QUERY_FETCH_FAILED = "SEARCH_QUERY_FETCH_FAILED";
export const SEARCH_QUERY_FETCH_RESET = "SEARCH_QUERY_FETCH_RESET";
